### ISSUE TITLE
CI build action

### ISSUE THREAD

**Issue by peter279k** [tighten/mailthief#96]
As title, it seems that the codeship CI will not action on oncoming PRs.

Could someone check this issue?

**Comment by mattstauffer** [comment]
Codeship only works on PRs coming from the project, not those from forks. It'd be worth checking whether that limitation isn't the case in Travis.

**Comment by peter279k** [comment]
Hi @mattstauffer, thanks for your reply.

As we can look at this [PR](https://github.com/tightenco/mailthief/pull/87), I don't find any CodeShip CI build status on this PR.

And it cannot be reliable for every PR is under verification on CI build.

**Comment by mattstauffer** [comment]
Right.. because the PR you linked to is from a fork.

**Comment by mattstauffer** [comment]
However, this PR: https://github.com/tightenco/mailthief/pull/95

Is not from a fork and also didn't have it run. That seems like a problem. And I'd love to go test whether Travis runs on fork pull requests, anyway.

**Comment by peter279k** [comment]
If the Travis CI build is enabled on this repo, I think it would be great for contributors :).

**Comment by mattstauffer** [comment]
Closed per #98
